// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Quiz_CoverImageColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Quiz_CoverImageColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201803050841291_Quiz_CoverImageColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
