// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Quiz_Version_RelatedChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Quiz_Version_RelatedChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201803210939331_Quiz_Version_RelatedChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
