// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuizReporting_JAS_189 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuizReporting_JAS_189));
        
        string IMigrationMetadata.Id
        {
            get { return "201804161221172_QuizReporting_JAS_189"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
