// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Company_addTertiaryColorAndCompanyId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Company_addTertiaryColorAndCompanyId));
        
        string IMigrationMetadata.Id
        {
            get { return "201810131225173_Company_addTertiaryColorAndCompanyId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
