// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Quiz_JAS_104_ResultSetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Quiz_JAS_104_ResultSetting));
        
        string IMigrationMetadata.Id
        {
            get { return "201803090652383_Quiz_JAS_104_ResultSetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
