// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkPackageInfo_Type_CampaignId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkPackageInfo_Type_CampaignId));
        
        string IMigrationMetadata.Id
        {
            get { return "201811200604072_WorkPackageInfo_Type_CampaignId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
