// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuizStats_JAS_97 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuizStats_JAS_97));
        
        string IMigrationMetadata.Id
        {
            get { return "201804040928399_QuizStats_JAS_97"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
