// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuizBrandingAndStyle_LogoUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuizBrandingAndStyle_LogoUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "202004230941314_QuizBrandingAndStyle_LogoUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
