// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuizResult_AddAutoPlay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuizResult_AddAutoPlay));
        
        string IMigrationMetadata.Id
        {
            get { return "202003060601415_QuizResult_AddAutoPlay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
