// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PendingApiQueue_RequestTypeURLandAuthorization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PendingApiQueue_RequestTypeURLandAuthorization));
        
        string IMigrationMetadata.Id
        {
            get { return "202010011418094_PendingApiQueue_RequestTypeURLandAuthorization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
